#!/bin/bash
cd /home/webonise/assignment;
fileCount = 0;

for i in *.txt;
do

  echo "enter new file name of $i";
  read filename;
  mv $i $filename;

done



for i in x*;
do

  echo "enter new file name of $i";
  read filename;
  mv $i $filename;
  echo "$filename"
  echo "$filename" >> /home/webonise/assignment.log
done
ls *.txt
ls *.txt >> /home/webonise/assignment.log
