#!/bin/bash
#Changes the current directory
cd /home/webonise/assignment;
#Appends the date and time into the assignment.log file
date >> /home/webonise/assignment.log

for i in *.txt;
do

  echo "enter new file name of $i";
  #Reads the new filename from the user
  read filename;
  #Renames the filename
  mv $i $filename;

done



for i in x*;
do

  echo "enter new file name of $i";
  read filename;
  mv $i $filename;
  echo "$filename"
  #Appends the renamed filename into assignment.log file
  echo "$filename" >> /home/webonise/assignment.log
done
#Lists all the file with .txt extension
ls *.txt
#Appends the filename with .txt extension in assignment.log
ls *.txt >> /home/webonise/assignment.log
