#!/bin/bash
echo "Date and Time"
#Prints Date and Time
date
echo "Hostname of system"
#Shows the systems hostname
hostname
echo "Type and version of the operating system"
#Prints the distribution specific information
lsb_release -a
echo "Full path to user's home Directory"
# ~ contains the path of home directory
echo ~
echo "Other users logged into the system"
#Prints the users currently logged into the system
users
echo "Groups user belongs to"
#Prints the group name
groups webonise
echo "Files in Home directory and subdirectory excluding directories"
#lists the files excluding directories
ls -R | grep -v "d"
