#!/bin/bash
#Creates directory public_html in home directory
mkdir ~/public_html
#Creates a file readme.txt in public_html directory
touch ~/public_html/readme.txt
#Changes files permission of user, groups and others of readme.txt
chmod 777 ~/public_html/readme.txt
